Peer Dependency Configuration
DallasHoff/sqlocal pull request #17
Opened 2024-01-27 21:51 UTC by DallasHoff

* Remove `kysely` from `dependencies`
* List `kysely` and `drizzle-orm` as `devDependencies` (needed for the tests) and `peerDependencies`
* Use `peerDependenciesMeta` to mark `kysely` and `drizzle-orm` as optional since one is only needed if using the Kysely dialect or Drizzle driver integrations of SQLocal

2024-01-29 08:50 UTC, singingwolfboy requested changes

2024-01-29 08:50 UTC, singingwolfboy commented on package.json
> +		"drizzle-orm": "^0.29.1"
Could you make these version specifiers looser? I would recommend `"*"`, although that may be _too_ loose for your taste. Keep in mind that the whole point of peer dependencies is that the developer using the library gets to specify the exact version they want to use, so peer deps _should_ have very loose specifiers -- the developer using the library can and should tighten them as needed.

2024-01-29 09:00 UTC, singingwolfboy commented
Also, maybe you should add something to the "Install" section of the README, to clarify that if you want to use the integrations with Kysely or Drizzle, you need to install those dependencies as well.

2024-02-03 05:07 UTC, DallasHoff commented on package.json
> +		"drizzle-orm": "^0.29.1"
Good call. Looks like the caret works differently for major version 0 packages and minor versions above these for Drizzle and Kysely actually would not have been installable. Changed.

2024-02-03 07:56 UTC, singingwolfboy approved these changes
Looks good! I still think it would be better to also include something in the README about installing these two optional deps, but that can also be done later if necessary.

2024-02-04 00:30 UTC, merged